import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: "2px" }}>
        {" "}
        <header
          style={{
            margin: 0,
            padding: "8px",
            borderBottom: "1px solid #f9f9f9",

            display: "flex",
            alignItems: "center",
            justifyContent: "start",
          }}
        >
          <Link
            href="/"
            style={{
              fontWeight: "normal",
              fontSize: "16px",
              textDecoration: "none",
              color: "#2563EB",
            }}
          >
            ← Back to Home
          </Link>
        </header>{" "}
        {children}
      </body>
    </html>
  );
}
